TYPE_NAME_ONE_DICT = {'国语': '语言&地域,国语,guoyu', '女声': '人声,女声,nvsheng', '青春': '风格,青春,qingchun',
                      '午后': '场景,午后,wuhou', '寂寞': '心情,寂寞,jimo', '70后': '年代,70后,70hou',
                      '酒吧': '场景,酒吧,jiuba', '钢琴曲': '乐器,钢琴曲,gangqinqu', '好听': '风格,好听,haoting',
                      '婚礼': '场景,婚礼,hunli', '轻音乐': '热门,轻音乐,qingyinle', '萨克斯': '乐器,萨克斯,sakesi',
                      '励志': '心情,励志,lizhi', '小清新': '风格,小清新,xiaoqingxin', '武侠': '主题,武侠,wuxia',
                      '古风': '主题,古风,gufeng', '咖啡厅': '场景,咖啡厅,kafeiting', '韩语': '语言&地域,韩语,hanyu',
                      '军旅歌曲': '主题,军旅歌曲,junlvgequ', '电子': '流派,电子,dianzi', '动漫': '影视节目,动漫,dongman',
                      '汽车': '场景,汽车,qiche', '童声': '人声,童声,tongsheng', '民歌': '热门,民歌,minge',
                      '美好': '心情,美好,meihao', 'DJ 舞曲': '热门,DJ 舞曲,djwuqu',
                      '中国好歌曲': '影视节目,中国好歌曲,zhongguohaogequ', '唯美': '风格,唯美,weimei',
                      '80后': '年代,80后,80hou', '欧美经典': '年代,欧美经典,oumeijingdian', '布鲁斯': '流派,布鲁斯,bulusi',
                      '欧美': '热门,欧美,oumei', '法语': '语言&地域,法语,fayu', '英文儿歌': '主题,英文儿歌,yingwenerge',
                      '管弦乐': '乐器,管弦乐,guanxianle', '格莱美': '主题,格莱美,gelaimei', '纯净': '风格,纯净,chunjing',
                      '流金岁月': '主题,流金岁月,liujinsuiyue', '怀念': '心情,怀念,huainian', '民谣': '流派,民谣,minyao',
                      '劲爆': '热门,劲爆,jinbao', '粤语': '热门,粤语,yueyu', '舒服': '心情,舒服,shufu',
                      '胎教': '主题,胎教,taijiao', '吉他': '乐器,吉他,jita', '交响乐': '风格,交响乐,jiaoxiangle',
                      '激情': '心情,激情,jiqing', '浪漫': '心情,浪漫,langman', '成名曲': '主题,成名曲,chengmingqu',
                      '古典音乐': '流派,古典音乐,gudianyinle', '中国风': '主题,中国风,zhongguofeng',
                      '安静': '心情,安静,anjing', '新世纪': '流派,新世纪,xinshiji', '网络歌曲': '主题,网络歌曲,wangluogequ',
                      '90年代': '年代,90年代,90niandai', '儿歌': '主题,儿歌,erge', '纯音乐': '乐器,纯音乐,chunyinle',
                      '经典老歌': '年代,经典老歌,jingdianlaoge', '印度': '语言&地域,印度,yindu', '想念': '心情,想念,xiangnian',
                      '摇滚': '流派,摇滚,yaogun', '甜蜜': '心情,甜蜜,tianmi', '闽南语': '语言&地域,闽南语,minnanyu',
                      '竖琴': '乐器,竖琴,shuqin', '喜悦': '心情,喜悦,xiyue', '草原歌曲': '热门,草原歌曲,caoyuangequ',
                      '旅行': '场景,旅行,lvxing', '伤感': '心情,伤感,shanggan', '新歌': '热门,新歌,xinge',
                      '日本动漫': '影视节目,日本动漫,ribendongman', '空灵': '人声,空灵,kongling', '90后': '年代,90后,90hou',
                      '中国好声音': '热门,中国好声音,zhongguohaoshengyin', '轻松': '心情,轻松,qingsong',
                      '天籁童声': '人声,天籁童声,tianzuotongsheng', '流行': '流派,流行,liuxing', '怀旧': '心情,怀旧,huaijiu',
                      '天籁': '人声,天籁,tianzuo', '校园': '场景,校园,xiaoyuan', '背景音乐': '场景,背景音乐,beijingyinle',
                      '情歌': '主题,情歌,qingge', '长笛': '乐器,长笛,changdi', '男高音': '人声,男高音,nangaoyin',
                      '日语': '语言&地域,日语,riyu', '小鲜肉': '人声,小鲜肉,xiaoxianrou', '口琴': '乐器,口琴,kouqin',
                      '电影': '影视节目,电影,dianying', '舒缓': '风格,舒缓,shuhuan', '深情': '心情,深情,shenqing',
                      '对唱': '人声,对唱,duichang', '电视剧': '影视节目,电视剧,dianshiju', '热歌': '热门,热歌,rege',
                      '爵士': '流派,爵士,jueshi', '慢摇': '风格,慢摇,manyao', '小提琴': '乐器,小提琴,xiaotiqin'}

TYPE_NAME_TWO_DICT = {'儿歌': '年代,儿歌,erge', '电视剧': '热门,电视剧,dianshiju', '劲爆': '风格,劲爆,jinbao',
                      '80后': '热门,80后,80hou', '萨克斯': '热门,萨克斯,sakesi', '纯音乐': '热门,纯音乐,chunyinle',
                      '欧美': '语言&地域,欧美,oumei', '轻音乐': '风格,轻音乐,qingyinle', '民歌': '风格,民歌,minge',
                      '成名曲': '热门,成名曲,chengmingqu', '古典音乐': '热门,古典音乐,gudianyinle',
                      '对唱': '热门,对唱,duichang', '经典老歌': '热门,经典老歌,jingdianlaoge',
                      '钢琴曲': '热门,钢琴曲,gangqinqu', 'DJ 舞曲': '风格,DJ 舞曲,djwuqu',
                      '网络歌曲': '热门,网络歌曲,wangluogequ', '粤语': '语言&地域,粤语,yueyu',
                      '欧美经典': '语言&地域,欧美经典,oumeijingdian', '草原歌曲': '语言&地域,草原歌曲,caoyuangequ'}

TYPE_NAME_THREE_DICT = {'儿歌': '热门,儿歌,erge'}

TYPE_OTHER_STR = '其它,其它,qita'